{{- if .Values.javaBackend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-java-backend
  labels:
    app: {{ .Release.Name }}-java-backend
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.javaBackend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-java-backend
{{- end }}
---
{{- if .Values.reactUi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.reactUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-ui
{{- end }}
---
{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-analytics
  labels:
    app: {{ .Release.Name }}-analytics
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.analytics.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-analytics
{{- end }}
